In [1]:
import pandas as pd
import requests
import json
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as sts
import csv
import seaborn as sns
from collections import Counter

import statistics as stats

from numpy.random import seed

import seaborn as sns; sns.set()

import os

import warnings

from scipy.stats import norm
from scipy.stats import t
from scipy.stats import ttest_ind_from_stats


from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.metrics import plot_roc_curve
from sklearn.datasets import load_wine
from sklearn.exceptions import ConvergenceWarning
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ParameterGrid
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import precision_score, recall_score, roc_auc_score, roc_curve
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier

#below will help understand the accuracy of the model
#F1 score, if within 75-90 percent range, then acceptable
from sklearn.metrics import classification_report

In [2]:
#Store CSV into Dataframe

df = "./Resources/train.csv"
train_df = pd.read_csv(df,encoding='latin-1')
train_df.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2.0,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0.0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3.0,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2.0,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1.0,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

In [3]:
#Remove null values 
train_df = train_df.dropna(how='any',axis=0)

In [4]:
#drop the loan id from the dataset, we do not need this for the machine learning models
train_df.drop('Loan_ID', axis=1, inplace=True)

In [5]:
# Turn all the categorical variables into numbers
from sklearn.preprocessing import LabelEncoder
category= ['Gender','Married','Dependents','Education','Self_Employed','Property_Area','Loan_Status']
encoder= LabelEncoder()
for i in category:
    train_df[i] = encoder.fit_transform(train_df[i])
    train_df.dtypes

In [6]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 480 entries, 1 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             480 non-null    int32
 1   Married            480 non-null    int32
 2   Dependents         480 non-null    int64
 3   Education          480 non-null    int32
 4   Self_Employed      480 non-null    int32
 5   ApplicantIncome    480 non-null    int64
 6   CoapplicantIncome  480 non-null    float64
 7   LoanAmount         480 non-null    float64
 8   Loan_Amount_Term   480 non-null    float64
 9   Credit_History     480 non-null    float64
 10  Property_Area      480 non-null    int32
 11  Loan_Status        480 non-null    int32
dtypes: float64(4), int32(6), int64(2)
memory usage: 37.5 KB

In [7]:
#random forest machine learning model
#get the train and test split and prepared
#split data into training and test sets
y = train_df['Loan_Status']
X = train_df.drop('Loan_Status', axis=1)

# Splitting the observations into a training and a testing set for the holdout method

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=46)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50)

In [8]:
# Min-max scaling for neural nets and SVMs

X_train_norm = preprocessing.normalize(X_train, norm='max', axis=0)  # Normalizing across columns
X_test_norm = preprocessing.normalize(X_test, norm='max', axis=0)  # Normalizing across columns

In [9]:
# Turn all the categorical variables into numbers
from sklearn.preprocessing import LabelEncoder
category= ['Gender','Married','Dependents','Education','Self_Employed','Property_Area','Loan_Status']
encoder= LabelEncoder()
for i in category:
    train_df[i] = encoder.fit_transform(train_df[i])
    train_df.dtypes

In [10]:
#random forest model
rf = RandomForestClassifier(n_estimators=500, n_jobs=-1)
rf.fit(X_train, y_train)
print(rf.score(X_test, y_test))
#pred = rf.predict(X_test)
#print(classification_report(y_test, pred))

0.7625

In [13]:
 import pickle

# #
# # Create your model here (same as above)
# #

# # Save to file in the current working directory
# rf_model = "rf_model.pkl"
# with open(rf_model, 'wb') as file:
#     pickle.dump(rf_model, file)

# # Load from file
# with open(rf_model, 'rb') as file:
#     pickle_model = pickle.load(file)
    
# # # Calculate the accuracy score and predict target values
# # score = rf_model.score(Xtest, Ytest)
# # print("Test score: {0:.2f} %".format(100 * score))
# # Ypredict = rf_model.predict(Xtest)

file='rf.sav'
pickle.dump(rf, open(file, 'wb'))
loaded_model = pickle.load(open(file, 'rb'))

In [14]:
#random forest model
rf = RandomForestClassifier(n_estimators=500, n_jobs=-1)
rf.fit(X_train, y_train)
print(rf.score(X_test, y_test))
pred = rf.predict(X_test)
print(classification_report(y_test, pred))

0.7583333333333333
              precision    recall  f1-score   support

           0       0.73      0.46      0.56        81
           1       0.77      0.91      0.83       159

    accuracy                           0.76       240
   macro avg       0.75      0.68      0.70       240
weighted avg       0.75      0.76      0.74       240